//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaSprint1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerOrder
    {
        [Key]
        public int OrderId { get; set; }
        public string OrderStatus { get; set; }
        public int CustomerId { get; set; }
        public int PizzaId { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual PizzaTable PizzaTable { get; set; }
    }
}
