//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaSprint1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class PizzaTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PizzaTable()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }

        [Key]//Denotes that it uniquely identifies the pizza
        public int PizzaId { get; set; }

        [DisplayName("Pizza Name")]
        [Required(ErrorMessage = "Name is required")]
        public string Pizzaname { get; set; }

        [DisplayName("Pizza Image")]
        [Required(ErrorMessage = "Image is required")]
        public string ImageUrl { get; set; }

        [DisplayName("Pizza Price")]
        [Required(ErrorMessage = "Price is required")]
        public int Price { get; set; }
        public HttpPostedFileBase imageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}
